### ISSUE TITLE
Quizlet starting when code run

### ISSUE THREAD

**Issue by BreadedApples** [jaeheonshim/quizlet-match-hack#3]
i solved it but i get undesireable times this is the edited code

document.getElementsByClassName("UIButton UIButton--hero")[0].onclick();
setTimeout(function(){for(var F = setTimeout(";"), i = 0; i < F; i++) clearTimeout(i)}, 5100); //Change 5100

//changed click to on click so it dont start it but i get undesireable times. pls help

**Comment by jaeheonshim** [comment]
Ummm... onclick() is used to set the javascript function that occurs when a user clicks on an element, it doesn't do anything else. I used the click() function so that the code would automatically click the start button. As I mentioned in the readme, you can get a faster time by changing the millisecond value as the second parameter of the setTimeout function. For example, here is a code that would get your time down to 1 second:

`document.getElementsByClassName("UIButton UIButton--hero")[0].click();
setTimeout(function(){for(var F = setTimeout(";"), i = 0; i < F; i++) clearTimeout(i)}, 1100);`

As you can see, I changed the number _5100_ to _1100_. Keep in mind that you can't go lower than 500, or 0.5 seconds. 

I hope I answered your question,
Jaeheon Shim

**Comment by BreadedApples** [comment]
thanks i realized that it works in micromatch, i tried it in normal match.
